CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,
	title VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist (
	id SERIAL PRIMARY KEY,
	nickname VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	title VARCHAR(120) NOT NULL,
	year_ INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS genre_artist (
	id SERIAL PRIMARY KEY,
	genre_id INTEGER REFERENCES Genre(id),
	artist_id INTEGER REFERENCES Artist(id)
);

CREATE TABLE IF NOT EXISTS artist_album (
	id SERIAL PRIMARY KEY,
	album_id INTEGER REFERENCES Album(id),
	artist_id INTEGER REFERENCES Artist(id)
);

CREATE TABLE IF NOT EXISTS Collection (
	id SERIAL PRIMARY KEY,
	name_ VARCHAR(60) NOT NULL,
	year_ INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Song (
	id SERIAL PRIMARY KEY,
	name_ VARCHAR(60) NOT NULL,
	duration INTEGER,
	album_id INTEGER REFERENCES Album(id),
	collection_id INTEGER REFERENCES Collection(id)
);

CREATE TABLE IF NOT EXISTS album_song (
	id SERIAL PRIMARY KEY,
	album_id INTEGER REFERENCES Album(id),
	song_id INTEGER REFERENCES Song(id)	
);
